#!/bin/bash
# Runs once at container boot (s6-rc oneshot). Two jobs:
#   1. Prepare /var/log/claworc and the claworc user's HOME.
#   2. Snapshot PID 1's env to /etc/environment and
#      /etc/profile.d/claworc-env.sh so SSH sessions — which go through
#      PAM and do NOT inherit sshd's env — see the vars passed to
#      `docker run -e` / the Kubernetes pod spec.
#
# s6 services themselves already inherit PID 1's env through their
# `#!/command/with-contenv bash` shebang; this script only fixes the
# sshd/login.defs path.

set -e

# ---------------------------------------------------------------------------
# SSH host keys: regenerate per-pod so every container has unique keys.
# The Dockerfile deletes baked-in keys; if any are missing, generate them.
# ssh-keygen -A creates only the key types that don't already exist, so this
# is a no-op on subsequent boots.
# ---------------------------------------------------------------------------
if command -v ssh-keygen >/dev/null 2>&1; then
    ssh-keygen -A >/dev/null 2>&1 || true
fi

# ---------------------------------------------------------------------------
# Filesystem + user home (unchanged from the prior inline one-liner)
# ---------------------------------------------------------------------------
mkdir -p /var/log/claworc
chmod 755 /var/log/claworc
test -f /home/claworc/.bashrc || cp -a /etc/skel/. /home/claworc/
mkdir -p /home/claworc/Downloads

# On the on-demand layout the agent pod has no Chromium and svc-desktop is
# absent — but the agent home volume may carry a leftover /home/claworc/chrome-data
# from a previous legacy combined image. Remove it so the agent's file
# manager / SSH session can't reach a stale browser profile that now lives
# in a separate browser pod. Skip on images that actually run the desktop
# (browser-base derivatives) — those legitimately need chrome-data.
if [ ! -e /etc/s6-overlay/s6-rc.d/user/contents.d/svc-desktop ]; then
    rm -rf /home/claworc/chrome-data
fi

chown -R claworc:claworc /home/claworc

# ---------------------------------------------------------------------------
# Propagate PID 1 env to PAM and bash login shells
# ---------------------------------------------------------------------------
# Exclude vars owned by the login shell / PAM / getpw — writing them
# here would either be overridden on login (USER, LOGNAME, MAIL) or
# actively wrong (HOME=/root for PID 1 vs. /home/claworc for the user).
exclude='^(PATH|HOME|HOSTNAME|TERM|PWD|OLDPWD|SHLVL|SHELL|LOGNAME|USER|MAIL|_)='

# /etc/environment: KEY="VALUE" pairs, read by pam_env. sshd's PAM stack on
# this image contains `session required pam_env.so`, so every SSH session
# inherits these. Values are double-quoted and backslash-escaped so that
# a literal `#` (comment), `$`, `"` or `\` in the value round-trips cleanly
# through pam_env's parser.
: > /etc/environment
printenv | grep -vE "$exclude" | while IFS='=' read -r key value; do
    # Escape \ then " for double-quoted context.
    escaped="${value//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    printf '%s="%s"\n' "$key" "$escaped" >> /etc/environment
done
chmod 644 /etc/environment

# /etc/profile.d/claworc-env.sh: sourced by every bash login shell (SSH
# defaults to login shells). Belt-and-suspenders for the rare PAM setups
# that skip pam_env, and for `bash -l` / `su -`. Values are quoted with
# `printf %q` so they round-trip through bash safely.
{
    echo '# Generated by init-setup.sh at container boot. Do not edit.'
    printenv | grep -vE "$exclude" | while IFS='=' read -r key value; do
        printf 'export %s=%q\n' "$key" "$value"
    done
} > /etc/profile.d/claworc-env.sh
chmod 644 /etc/profile.d/claworc-env.sh
